let engWords = [{'eng' : 'hi', 'transcription' : '[хай]', 'rus' : 'привет'},
{'eng' : 'hello', 'transcription' : '[хэлОу]', 'rus' : 'здравствуйте, привет'},
{'eng' : 'sorry', 'transcription' : '[сOри]', 'rus' : 'извини(те)'},
{'eng' : 'please', 'transcription' : '[пли:з]', 'rus' : 'пожалуйста (прошу); угождать'},
{'eng' : 'thank you', 'transcription' : '[сэнк ю]', 'rus' : 'спасибо'},
{'eng' : 'you are welcome', 'transcription' : '[ю: а уЭлкэм]', 'rus' : 'пожалуйста, не за что'},
{'eng' : 'what a pity', 'transcription' : '[уот э пИти]', 'rus' : 'как жаль'},
{'eng' : '(good)bye', 'transcription' : '[(гуд)бAй]', 'rus' : 'до свидания'},
{'eng' : 'people', 'transcription' : '[пи:пл]', 'rus' : 'люди'},
{'eng' : 'man', 'transcription' : '[мэн]', 'rus' : 'мужчина'},
{'eng' : 'woman', 'transcription' : '[уУмэн]', 'rus' : 'женщина'},
{'eng' : 'child', 'transcription' : '[чайлд]', 'rus' : 'ребенок'},
{'eng' : 'boy', 'transcription' : '[бой]', 'rus' : 'мальчик'},
{'eng' : 'girl', 'transcription' : '[гё:рл]', 'rus' : 'девочка'},
{'eng' : 'guy', 'transcription' : '[гай]', 'rus' : 'парень'},
{'eng' : 'friend', 'transcription' : '[фрэнд]', 'rus' : 'друг'},
{'eng' : 'acquaintance', 'transcription' : '[экуЭйнтэнс]', 'rus' : 'знакомый; знакомство'},
{'eng' : 'neighbor', 'transcription' : '[нЭйбэр]', 'rus' : 'сосед'},
{'eng' : 'guest', 'transcription' : '[гэст]', 'rus' : 'гость'},
{'eng' : 'chief', 'transcription' : '[чи:ф]', 'rus' : 'начальник; шеф; главный; вождь'},
{'eng' : 'boss', 'transcription' : '[бос]', 'rus' : 'босс'},
{'eng' : 'competitor', 'transcription' : '[кэмпЭтитэр]', 'rus' : 'конкурент, соперник'},
{'eng' : 'client', 'transcription' : '[клАйэнт]', 'rus' : 'клиент'},
{'eng' : 'colleague', 'transcription' : '[кОли:г]', 'rus' : 'коллега'},
{'eng' : 'family', 'transcription' : '[фЭмили]', 'rus' : 'семья'},
{'eng' : 'parents', 'transcription' : '[пЭэрэнтс]', 'rus' : 'родители'},
{'eng' : 'father', 'transcription' : '[фА:зэр]', 'rus' : 'отец'},
{'eng' : 'dad(dy)', 'transcription' : '[дЭд(и)]', 'rus' : 'папа'},
{'eng' : 'mother', 'transcription' : '[мАзэр]', 'rus' : 'мать'},
{'eng' : 'mum(my)', 'transcription' : '[мам(и)]', 'rus' : 'мама'},
{'eng' : 'husband', 'transcription' : '[хАзбэнд]', 'rus' : 'муж'},
{'eng' : 'wife', 'transcription' : '[уАйф]', 'rus' : 'жена'},
{'eng' : 'son', 'transcription' : '[сан]', 'rus' : 'сын'},
{'eng' : 'daughter', 'transcription' : '[дО:тэр]', 'rus' : 'дочь'},
{'eng' : 'brother', 'transcription' : '[брАзэр]', 'rus' : 'брат'},
{'eng' : 'sister', 'transcription' : '[сИстэр]', 'rus' : 'сестра'},
{'eng' : 'grandfather', 'transcription' : '[грЭнфА:зэр]', 'rus' : 'дед ...'},
{'eng' : 'father-in-law', 'transcription' : '[фА:зэр ин лО:]', 'rus' : 'тесть, свекор ...'},
{'eng' : 'uncle', 'transcription' : '[анкл]', 'rus' : 'дядя'},
{'eng' : 'aunt', 'transcription' : '[а:нт]', 'rus' : 'тетя'},
{'eng' : 'cousin', 'transcription' : '[казн]', 'rus' : 'двоюродный брат, двоюродная сестра'},
{'eng' : 'nephew', 'transcription' : '[нЭфъю:]', 'rus' : 'племянник'},
{'eng' : 'niece', 'transcription' : '[ни:с]', 'rus' : 'племянница'},
{'eng' : 'job', 'transcription' : '[джоб]', 'rus' : 'работа'},
{'eng' : 'businessman', 'transcription' : '[бИзнэсмэн]', 'rus' : 'бизнесмен'},
{'eng' : 'teacher', 'transcription' : '[тИ:чэр]', 'rus' : 'учитель'},
{'eng' : 'driver', 'transcription' : '[дрАйвэр]', 'rus' : 'водитель'},
{'eng' : 'worker', 'transcription' : '[уО:ркэр]', 'rus' : 'рабочий'},
{'eng' : 'engineer', 'transcription' : '[энджинИ:эр]', 'rus' : 'инженер'},
{'eng' : 'doctor', 'transcription' : '[дОктэр]', 'rus' : 'врач'},
{'eng' : 'lawyer', 'transcription' : '[лО:ер]', 'rus' : 'адвокат, юрист'},
{'eng' : 'journalist', 'transcription' : '[джЁ:рнэлист]', 'rus' : 'журналист'},
{'eng' : 'nurse', 'transcription' : '[нё:рс]', 'rus' : 'медсестра'},
{'eng' : 'shop assistаnt', 'transcription' : '[шОп эсИстэнт]', 'rus' : 'продавец'},
{'eng' : 'waiter', 'transcription' : '[уЭйтэр]', 'rus' : 'официант'},
{'eng' : 'accountant', 'transcription' : '[экАунтэнт]', 'rus' : 'бухгалтер'},
{'eng' : 'artist', 'transcription' : '[А:ртист]', 'rus' : 'художник'},
{'eng' : 'musician', 'transcription' : '[мъю:зИшн]', 'rus' : 'музыкант'},
{'eng' : 'actor', 'transcription' : '[Эктэр]', 'rus' : 'актер'},
{'eng' : 'student', 'transcription' : '[стъЮдэнт]', 'rus' : 'студент'},
{'eng' : 'pupil', 'transcription' : '[пъюпл]', 'rus' : 'школьник, ученик'},
{'eng' : 'animal', 'transcription' : '[Энимэл]', 'rus' : 'животное'},
{'eng' : 'cat', 'transcription' : '[кэт]', 'rus' : 'кошка'},
{'eng' : 'dog', 'transcription' : '[дог]', 'rus' : 'собака'},
{'eng' : 'bird', 'transcription' : '[бё:рд]', 'rus' : 'птица'},
{'eng' : 'squirrel', 'transcription' : '[скуИрэл]', 'rus' : 'белка'},
{'eng' : 'wolf', 'transcription' : '[уулф]', 'rus' : 'волк'},
{'eng' : 'goose', 'transcription' : '[гу:с]', 'rus' : 'гусь'},
{'eng' : 'giraffe', 'transcription' : '[джирА:ф]', 'rus' : 'жираф'},
{'eng' : 'rabbit', 'transcription' : '[рЭбит]', 'rus' : 'кролик; заяц'},
{'eng' : 'cow', 'transcription' : '[кАу]', 'rus' : 'корова'},
{'eng' : 'rat', 'transcription' : '[рЭт]', 'rus' : 'крыса'},
{'eng' : 'fox', 'transcription' : '[фокс]', 'rus' : 'лиса'},
{'eng' : 'horse', 'transcription' : '[хо:рс]', 'rus' : 'лошадь'},
{'eng' : 'frog', 'transcription' : '[фрог]', 'rus' : 'лягушка'},
{'eng' : 'bear', 'transcription' : '[бЭэр]', 'rus' : 'медведь'},
{'eng' : 'mouse', 'transcription' : '[мАус]', 'rus' : 'мышь'},
{'eng' : 'monkey', 'transcription' : '[мАнки]', 'rus' : 'обезьяна'},
{'eng' : 'pig', 'transcription' : '[пиг]', 'rus' : 'свинья'},
{'eng' : 'elephant', 'transcription' : '[Элэфэнт]', 'rus' : 'слон'},
{'eng' : 'duck', 'transcription' : '[дак]', 'rus' : 'утка'},
{'eng' : 'country', 'transcription' : '[кантри]', 'rus' : 'страна; сельская местность'},
{'eng' : 'Russia', 'transcription' : '[рАшэ]', 'rus' : 'Россия'},
{'eng' : 'Great Britain', 'transcription' : '[грЭйт брИтэн]', 'rus' : 'Великобритания'},
{'eng' : 'England', 'transcription' : '[Инглэнд]', 'rus' : 'Англия'},
{'eng' : 'city', 'transcription' : '[сИти]', 'rus' : 'город'},
{'eng' : 'house', 'transcription' : '[хАус]', 'rus' : 'дом (здание)'},
{'eng' : 'home', 'transcription' : '[хОум]', 'rus' : 'дом (место проживания)'},
{'eng' : 'building', 'transcription' : '[бИлдинг]', 'rus' : 'здание; строительство'},
{'eng' : 'place', 'transcription' : '[плэйс]', 'rus' : 'место; помещать'},
{'eng' : 'entrance', 'transcription' : '[Энтрэнс]', 'rus' : 'вход'},
{'eng' : 'exit', 'transcription' : '[Эгзит]', 'rus' : 'выход'},
{'eng' : 'center', 'transcription' : '[сЭнтэр]', 'rus' : 'центр'},
{'eng' : 'yard', 'transcription' : '[я:рд]', 'rus' : 'двор'},
{'eng' : 'roof', 'transcription' : '[ру:ф]', 'rus' : 'крыша'},
{'eng' : 'fence', 'transcription' : '[фэнс]', 'rus' : 'забор'},
{'eng' : 'land', 'transcription' : '[лэнд]', 'rus' : 'земля, участок'},
{'eng' : 'village', 'transcription' : '[вИлидж]', 'rus' : 'деревня, поселок'},
{'eng' : 'school', 'transcription' : '[ску:л]', 'rus' : 'школа'},
{'eng' : 'university', 'transcription' : '[юнивЁ:рсити]', 'rus' : 'университет'},
{'eng' : 'theater', 'transcription' : '[сИ:этэр]', 'rus' : 'театр'},
{'eng' : 'church', 'transcription' : '[чё:рч]', 'rus' : 'церковь'},
{'eng' : 'restaurant', 'transcription' : '[рЭстронт]', 'rus' : 'ресторан'},
{'eng' : 'cafe', 'transcription' : '[кЭфэй]', 'rus' : 'кафе'},
{'eng' : 'hotel', 'transcription' : '[хоутЭл]', 'rus' : 'гостиница'},
{'eng' : 'bank', 'transcription' : '[бэнк]', 'rus' : 'банк'},
{'eng' : 'cinema', 'transcription' : '[сИнэмэ]', 'rus' : 'кинотеатр'},
{'eng' : 'hospital', 'transcription' : '[хОспитл]', 'rus' : 'больница'},
{'eng' : 'police', 'transcription' : '[пОлис]', 'rus' : 'полиция'},
{'eng' : 'post office', 'transcription' : '[пОуст Офис]', 'rus' : 'почта'},
{'eng' : 'station', 'transcription' : '[стэйшн]', 'rus' : 'станция, вокзал'},
{'eng' : 'airport', 'transcription' : '[Ээпо:рт]', 'rus' : 'аэропорт'},
{'eng' : 'shop', 'transcription' : '[шоп]', 'rus' : 'магазин'},
{'eng' : 'pharmacy', 'transcription' : '[фА:рмаси]', 'rus' : 'аптека'},
{'eng' : 'market', 'transcription' : '[мА:ркит]', 'rus' : 'рынок'},
{'eng' : 'office', 'transcription' : '[Офис]', 'rus' : 'офис'},
{'eng' : 'company', 'transcription' : '[кОмпэни]', 'rus' : 'компания, фирма'},
{'eng' : 'factory', 'transcription' : '[фЭктэри]', 'rus' : 'предприятие, завод, фабрика'},
{'eng' : 'square', 'transcription' : '[скуЭэр]', 'rus' : 'площадь'},
{'eng' : 'street', 'transcription' : '[стри:т]', 'rus' : 'улица'},
{'eng' : 'road', 'transcription' : '[рОуд]', 'rus' : 'дорога'},
{'eng' : 'crossroads', 'transcription' : '[крОсроудз]', 'rus' : 'перекрёсток'},
{'eng' : 'stop', 'transcription' : '[стоп]', 'rus' : 'остановка; останавливаться'},
{'eng' : 'sidewalk', 'transcription' : '[сАйдуо:к]', 'rus' : 'тротуар'},
{'eng' : 'path', 'transcription' : '[па:с]', 'rus' : 'тропа, тропинка'},
{'eng' : 'garden', 'transcription' : '[га:рдн]', 'rus' : 'сад'},
{'eng' : 'park', 'transcription' : '[па:рк]', 'rus' : 'парк'},
{'eng' : 'bridge', 'transcription' : '[бридж]', 'rus' : 'мост'},
{'eng' : 'river', 'transcription' : '[рИвэр]', 'rus' : 'река'},
{'eng' : 'forest', 'transcription' : '[фОрист]', 'rus' : 'лес'},
{'eng' : 'field', 'transcription' : '[фи:лд]', 'rus' : 'поле'},
{'eng' : 'mountain', 'transcription' : '[мАунтин]', 'rus' : 'гора'},
{'eng' : 'lake', 'transcription' : '[лэйк]', 'rus' : 'озеро'},
{'eng' : 'sea', 'transcription' : '[си:]', 'rus' : 'море'},
{'eng' : 'ocean', 'transcription' : '[Оушн]', 'rus' : 'океан'},
{'eng' : 'coast', 'transcription' : '[кОуст]', 'rus' : 'морской берег, побережье'},
{'eng' : 'beach', 'transcription' : '[би:ч]', 'rus' : 'пляж'},
{'eng' : 'sand', 'transcription' : '[сэнд]', 'rus' : 'песок'},
{'eng' : 'island', 'transcription' : '[Айлэнд]', 'rus' : 'остров'},
{'eng' : 'border', 'transcription' : '[бО:рдэр]', 'rus' : 'граница'},
{'eng' : 'customs', 'transcription' : '[кАстэмз]', 'rus' : 'таможня'},
{'eng' : 'garbage', 'transcription' : '[гА:рбидж]', 'rus' : 'мусор'},
{'eng' : 'waste', 'transcription' : '[уэйст]', 'rus' : 'отходы; тратить впустую'},
{'eng' : 'stone', 'transcription' : '[стОун]', 'rus' : 'камень'},
{'eng' : 'plant', 'transcription' : '[плА:нт]', 'rus' : 'растение; завод; сажать'},
{'eng' : 'tree', 'transcription' : '[три:]', 'rus' : 'дерево'},
{'eng' : 'grass', 'transcription' : '[гра:с]', 'rus' : 'трава'},
{'eng' : 'flower', 'transcription' : '[флАуэр]', 'rus' : 'цветокleaf', 'transcription' : '[ли:ф]', 'rus' : 'лист (дерева)'},
{'eng' : 'flat', 'transcription' : '[флэт]', 'rus' : 'квартира'},
{'eng' : 'room', 'transcription' : '[рум]', 'rus' : 'комната'},
{'eng' : 'living room', 'transcription' : '[лИвинг рум]', 'rus' : 'зал'},
{'eng' : 'bedroom', 'transcription' : '[бЭдрум]', 'rus' : 'спальня'},
{'eng' : 'bathroom', 'transcription' : '[бА:срум]', 'rus' : 'ванная'},
{'eng' : 'shower', 'transcription' : '[шАуэр]', 'rus' : 'душ'},
{'eng' : 'toilet', 'transcription' : '[тОйлит]', 'rus' : 'туалет'},
{'eng' : 'kitchen', 'transcription' : '[кИтчин]', 'rus' : 'кухня'},
{'eng' : 'hall', 'transcription' : '[хо:л]', 'rus' : 'коридор'},
{'eng' : 'balcony', 'transcription' : '[бЭлкони]', 'rus' : 'балкон'},
{'eng' : 'floor', 'transcription' : '[фло:р]', 'rus' : 'пол; этаж'},
{'eng' : 'ceiling', 'transcription' : '[сИ:линг]', 'rus' : 'потолок'},
{'eng' : 'wall', 'transcription' : '[уО:л]', 'rus' : 'стена'},
{'eng' : 'stairs', 'transcription' : '[стЭэрз]', 'rus' : 'ступеньки; лестница'},
{'eng' : 'door', 'transcription' : '[до:р]', 'rus' : 'дверь'},
{'eng' : 'window', 'transcription' : '[уИндоу]', 'rus' : 'окно'},
{'eng' : 'windowsill', 'transcription' : '[уИндоусил]', 'rus' : 'подоконник'},
{'eng' : 'curtain', 'transcription' : '[кЁртэн]', 'rus' : 'занавес(ка), штора'},
{'eng' : 'switch', 'transcription' : '[cуИч]', 'rus' : 'выключатель; переключать'},
{'eng' : 'socket', 'transcription' : '[сОкит]', 'rus' : 'розетка'},
{'eng' : 'faucet', 'transcription' : '[фО:сит]', 'rus' : '(водопроводный) кран'},
{'eng' : 'pipe', 'transcription' : '[пайп]', 'rus' : 'труба; трубка'},
{'eng' : 'chimney', 'transcription' : '[чИмни]', 'rus' : 'дымовая труба'},
{'eng' : 'furniture', 'transcription' : '[фЁ:ничэ]', 'rus' : 'мебель'},
{'eng' : 'table', 'transcription' : '[тэйбл]', 'rus' : 'стол'},
{'eng' : 'chair', 'transcription' : '[чЭэр]', 'rus' : 'стул'},
{'eng' : 'armchair', 'transcription' : '[А:рмчээр]', 'rus' : 'кресло'},
{'eng' : 'sofa', 'transcription' : '[сОуфа]', 'rus' : 'диван'},
{'eng' : 'bed', 'transcription' : '[бэд]', 'rus' : 'кровать'},
{'eng' : 'wardrobe', 'transcription' : '[уО:дроуб]', 'rus' : '(платяной) шкаф'},
{'eng' : 'cabinet', 'transcription' : '[кЭбинэт]', 'rus' : 'шкаф(чик)'},
{'eng' : 'shelf', 'transcription' : '[шэлф]', 'rus' : 'полка'},
{'eng' : 'mirror', 'transcription' : '[мИрор]', 'rus' : 'зеркало'},
{'eng' : 'carpet', 'transcription' : '[кА:рпит]', 'rus' : 'ковер'},
{'eng' : 'fridge', 'transcription' : '[фридж]', 'rus' : 'холодильник'},
{'eng' : 'microwave', 'transcription' : '[мАйкроууэйв]', 'rus' : 'микроволновка'},
{'eng' : 'oven', 'transcription' : '[Авэн]', 'rus' : 'печь, духовка'},
{'eng' : 'stove', 'transcription' : '[стОув]', 'rus' : 'кухонная плита'},
{'eng' : 'food', 'transcription' : '[фу:д]', 'rus' : 'еда'},
{'eng' : 'bread', 'transcription' : '[брэд]', 'rus' : 'хлеб'},
{'eng' : 'butter', 'transcription' : '[бАтэр]', 'rus' : 'масло'},
{'eng' : 'oil', 'transcription' : '[ойл]', 'rus' : 'растительное масло; нефть'},
{'eng' : 'cheese', 'transcription' : '[чи:з]', 'rus' : 'сыр'},
{'eng' : 'sausage', 'transcription' : '[сОсидж]', 'rus' : 'колбаса, сосиска'},
{'eng' : 'ham', 'transcription' : '[хэм]', 'rus' : 'ветчина'},
{'eng' : 'meat', 'transcription' : '[ми:т]', 'rus' : 'мясо'},
{'eng' : 'beef', 'transcription' : '[би:ф]', 'rus' : 'говядина'},
{'eng' : 'pork', 'transcription' : '[по:рк]', 'rus' : 'свинина'},
{'eng' : 'lamb', 'transcription' : '[лэм]', 'rus' : 'баранина; ягненок'},
{'eng' : 'chicken', 'transcription' : '[чИкин]', 'rus' : 'цыпленок; курица'},
{'eng' : 'cutlet', 'transcription' : '[кАтлит]', 'rus' : 'котлета'},
{'eng' : 'fish', 'transcription' : '[фиш]', 'rus' : 'рыба; рыбачить'},
{'eng' : 'egg', 'transcription' : '[эг]', 'rus' : 'яйцо'},
{'eng' : 'salad', 'transcription' : '[сЭлэд]', 'rus' : 'салат'},
{'eng' : 'mushroom', 'transcription' : '[мАшрум]', 'rus' : 'гриб'},
{'eng' : 'corn', 'transcription' : '[ко:рн]', 'rus' : 'кукуруза; зерно'},
{'eng' : 'porridge', 'transcription' : '[пОридж]', 'rus' : 'каша'},
{'eng' : 'oatmeal', 'transcription' : '[Оутми:л]', 'rus' : 'овсянка'},
{'eng' : 'soup', 'transcription' : '[су:п]', 'rus' : 'суп'},
{'eng' : 'sandwich', 'transcription' : '[сЭндуич]', 'rus' : 'бутерброд'},
{'eng' : 'rice', 'transcription' : '[райс]', 'rus' : 'рис'},
{'eng' : 'noodles', 'transcription' : '[ну:длз]', 'rus' : 'лапша'},
{'eng' : 'flour', 'transcription' : '[флАуэр]', 'rus' : 'мука'},
{'eng' : 'spice', 'transcription' : '[спайс]', 'rus' : 'специя, пряность'},
{'eng' : 'pepper', 'transcription' : '[пЭпэр]', 'rus' : 'перец; поперчить'},
{'eng' : 'salt', 'transcription' : '[со:лт]', 'rus' : 'соль; посолить'},
{'eng' : 'onion', 'transcription' : '[Аниэн]', 'rus' : 'лук (репчатый)'},
{'eng' : 'garlic', 'transcription' : '[гА:рлик]', 'rus' : 'чеснок'},
{'eng' : 'sauce', 'transcription' : '[сО:с]', 'rus' : 'соус'},
{'eng' : 'vegetables', 'transcription' : '[вЭджитэблз]', 'rus' : 'овощи'},
{'eng' : 'potatoes', 'transcription' : '[потЭйтоуз]', 'rus' : 'картофель'},
{'eng' : 'carrot', 'transcription' : '[кЭрэт]', 'rus' : 'морковь'},
{'eng' : 'beet', 'transcription' : '[би:т]', 'rus' : 'свекла'},
{'eng' : 'tomato', 'transcription' : '[томA:тоу]', 'rus' : 'помидор'},
{'eng' : 'cucumber', 'transcription' : '[къЮкамбэр]', 'rus' : 'огурец'},
{'eng' : 'cabbage', 'transcription' : '[кЭбидж]', 'rus' : 'капуста'},
{'eng' : 'squash', 'transcription' : '[скуОш]', 'rus' : 'кабачок'},
{'eng' : 'eggplant', 'transcription' : '[Эгпла:нт]', 'rus' : 'баклажан'},
{'eng' : 'beans', 'transcription' : '[би:нз]', 'rus' : 'бобы'},
{'eng' : 'pea', 'transcription' : '[пи:]', 'rus' : 'горох'},
{'eng' : 'nut', 'transcription' : '[нат]', 'rus' : 'орех'},
{'eng' : 'fruit', 'transcription' : '[фру:т]', 'rus' : 'фрукт(ы); плод'},
{'eng' : 'apple', 'transcription' : '[эпл]', 'rus' : 'яблоко'},
{'eng' : 'pear', 'transcription' : '[пЭэр]', 'rus' : 'груша'},
{'eng' : 'banana', 'transcription' : '[бэнЭнэ]', 'rus' : 'банан'},
{'eng' : 'berry', 'transcription' : '[бЭри]', 'rus' : 'ягода'},
{'eng' : 'strawberry', 'transcription' : '[стрО:бэри]', 'rus' : 'клубника, земляника'},
{'eng' : 'raspberry', 'transcription' : '[рА:збэри]', 'rus' : 'малина'},
{'eng' : 'cherry', 'transcription' : '[чЭри]', 'rus' : 'вишня'},
{'eng' : 'plum', 'transcription' : '[плам]', 'rus' : 'слива'},
{'eng' : 'grape', 'transcription' : '[грэйп]', 'rus' : 'виноград'},
{'eng' : 'apricot', 'transcription' : '[Эйприкот]', 'rus' : 'абрикос'},
{'eng' : 'peach', 'transcription' : '[пи:ч]', 'rus' : 'персик'},
{'eng' : 'melon', 'transcription' : '[мЭлон]', 'rus' : 'дыня'},
{'eng' : 'watermelon', 'transcription' : '[уOтэрмэлэн]', 'rus' : 'арбуз'},
{'eng' : 'pumpkin', 'transcription' : '[пАмпкин]', 'rus' : 'тыква'},
{'eng' : 'orange', 'transcription' : '[Oриндж]', 'rus' : 'апельсин; оранжевый'},
{'eng' : 'mandarin', 'transcription' : '[мЭндэрин]', 'rus' : 'мандарин'},
{'eng' : 'lemon', 'transcription' : '[лЭмон]', 'rus' : 'лимон'},
{'eng' : 'pineapple', 'transcription' : '[пАйнэпл]', 'rus' : 'ананас'},
{'eng' : 'sugar', 'transcription' : '[шУгэ]', 'rus' : 'сахар'},
{'eng' : 'honey', 'transcription' : '[хАни]', 'rus' : 'мёд'},
{'eng' : 'jam', 'transcription' : '[джэм]', 'rus' : 'варенье'},
{'eng' : 'cake', 'transcription' : '[кэйк]', 'rus' : 'торт'},
{'eng' : 'bun', 'transcription' : '[бан]', 'rus' : 'булочка'},
{'eng' : 'cookie', 'transcription' : '[кУки]', 'rus' : 'печенье'},
{'eng' : 'pie', 'transcription' : '[пай]', 'rus' : 'пирог, пирожок'},
{'eng' : 'sweet', 'transcription' : '[суи:т]', 'rus' : 'конфета; сладкий'},
{'eng' : 'ice-cream', 'transcription' : '[Aйскри:м]', 'rus' : 'мороженое'},
{'eng' : 'chocolate', 'transcription' : '[чOклит]', 'rus' : 'шоколад'},
{'eng' : 'water', 'transcription' : '[уотэр]', 'rus' : 'вода; поливать'},
{'eng' : 'soda', 'transcription' : '[сOуда]', 'rus' : 'газировка'},
{'eng' : 'juice', 'transcription' : '[джу:с]', 'rus' : 'сок'},
{'eng' : 'wine', 'transcription' : '[уайн]', 'rus' : 'вино'},
{'eng' : 'tea', 'transcription' : '[ти:]', 'rus' : 'чай'},
{'eng' : 'coffee', 'transcription' : '[кOфи]', 'rus' : 'кофе'},
{'eng' : 'milk', 'transcription' : '[милк]', 'rus' : 'молоко'},
{'eng' : 'cream', 'transcription' : '[кри:м]', 'rus' : 'сливки; крем'},
{'eng' : 'yogurt', 'transcription' : '[йОгэт]', 'rus' : 'йогурт'},
{'eng' : 'curd', 'transcription' : '[кЁ:рд]', 'rus' : 'творог'},
{'eng' : 'dish', 'transcription' : '[диш]', 'rus' : 'блюдо, посуда)'},
{'eng' : 'cup', 'transcription' : '[кап]', 'rus' : 'чашка'},
{'eng' : 'glass', 'transcription' : '[гла:с]', 'rus' : 'стакан; стекло'},
{'eng' : 'mug', 'transcription' : '[маг]', 'rus' : 'кружка'},
{'eng' : 'plate', 'transcription' : '[плэйт]', 'rus' : 'тарелка'},
{'eng' : 'spoon', 'transcription' : '[спу:н]', 'rus' : 'ложка'},
{'eng' : 'fork', 'transcription' : '[фо:рк]', 'rus' : 'вилка '},
{'eng' : 'knife', 'transcription' : '[найф]', 'rus' : 'нож'},
{'eng' : 'saucer', 'transcription' : '[сO:сэр]', 'rus' : 'блюдце'},
{'eng' : 'bottle', 'transcription' : '[ботл]', 'rus' : 'бутылка'},
{'eng' : 'napkin', 'transcription' : '[нЭпкин]', 'rus' : 'салфетка'},
{'eng' : 'pan', 'transcription' : '[пэн]', 'rus' : 'кастрюля'},
{'eng' : 'frying pan', 'transcription' : '[фрАйинг пэн]', 'rus' : 'сковородка'},
{'eng' : 'kettle', 'transcription' : '[кэтл]', 'rus' : 'чайник; котел'},
{'eng' : 'meal', 'transcription' : '[ми:л]', 'rus' : 'принятие пищи, еда'},
{'eng' : 'breakfast', 'transcription' : '[брЭкфэст]', 'rus' : 'завтрак'},
{'eng' : 'lunch', 'transcription' : '[ланч]', 'rus' : 'обед'},
{'eng' : 'dinner', 'transcription' : '[дИнэр]', 'rus' : 'ужин'},
{'eng' : 'transport', 'transcription' : '[трЭнспо:рт]', 'rus' : 'транспорт;', 'transcription' : '[трэнспО:рт]', 'rus' : 'перевозить, транспортировать'},
{'eng' : 'plane', 'transcription' : '[плэйн]', 'rus' : 'самолет'},
{'eng' : 'car', 'transcription' : '[ка:р]', 'rus' : 'автомобиль'},
{'eng' : 'tram', 'transcription' : '[трэм]', 'rus' : 'трамвай'},
{'eng' : 'bus', 'transcription' : '[бас]', 'rus' : 'автобус'},
{'eng' : 'train', 'transcription' : '[трэйн]', 'rus' : 'поезд'},
{'eng' : 'ship', 'transcription' : '[шип]', 'rus' : 'корабль'},
{'eng' : 'bicycle', 'transcription' : '[бAйсикл]', 'rus' : 'велосипед'},
{'eng' : 'time', 'transcription' : '[тайм]', 'rus' : 'время; раз'},
{'eng' : 'minute', 'transcription' : '[мИнит]', 'rus' : 'минута'},
{'eng' : 'hour', 'transcription' : '[Aуэр]', 'rus' : 'час'},
{'eng' : 'week', 'transcription' : '[уи:к]', 'rus' : 'неделя'},
{'eng' : 'year', 'transcription' : '[йИэр]', 'rus' : 'год'},
{'eng' : 'century', 'transcription' : '[сЭнчэри]', 'rus' : 'век, столетие'},
{'eng' : 'the day before yesterday', 'transcription' : '[зэ дэй бифО:р йЭстэдэй]', 'rus' : 'позавчера'},
{'eng' : 'yesterday', 'transcription' : '[йЭстэдэй]', 'rus' : 'вчера'},
{'eng' : 'today', 'transcription' : '[тудЭй]', 'rus' : 'сегодня (днем)'},
{'eng' : 'tonight', 'transcription' : '[тунАйт]', 'rus' : 'сегодня вечером (ночью)'},
{'eng' : 'tomorrow', 'transcription' : '[томОроу]', 'rus' : 'завтра'},
{'eng' : 'the day after tomorrow', 'transcription' : '[зэ дэй А:фтэр томОроу]', 'rus' : 'послезавтра'},
{'eng' : 'day', 'transcription' : '[дэй]', 'rus' : 'день'},
{'eng' : 'morning', 'transcription' : '[мо:рнинг]', 'rus' : 'утро'},
{'eng' : 'afternoon', 'transcription' : '[а:фтэрнУ:н]', 'rus' : 'день (после полудня)'},
{'eng' : 'evening', 'transcription' : '[И:внинг]', 'rus' : 'вечер'},
{'eng' : 'night', 'transcription' : '[найт]', 'rus' : 'ночь'},
{'eng' : 'Monday', 'transcription' : '[мAндэй]', 'rus' : 'понедельник'},
{'eng' : 'Tuesday', 'transcription' : '[тъЮ:здэй]', 'rus' : 'вторник'},
{'eng' : 'Wednesday', 'transcription' : '[уЭнздэй]', 'rus' : 'среда'},
{'eng' : 'Thursday', 'transcription' : '[сё:рздэй]', 'rus' : 'четверг'},
{'eng' : 'Friday', 'transcription' : '[фрAйдэй]', 'rus' : 'пятница'},
{'eng' : 'Saturday', 'transcription' : '[сЭтэрдэй]', 'rus' : 'суббота'},
{'eng' : 'Sunday', 'transcription' : '[сAндэй]', 'rus' : 'воскресенье'},
{'eng' : 'month', 'transcription' : '[манс]', 'rus' : 'месяц'},
{'eng' : 'January', 'transcription' : '[джЭнъюэри]', 'rus' : 'январь'},
{'eng' : 'February', 'transcription' : '[фЭбруэри]', 'rus' : 'февраль'},
{'eng' : 'March', 'transcription' : '[ма:рч]', 'rus' : 'март'},
{'eng' : 'April', 'transcription' : '[Эйприл]', 'rus' : 'апрель'},
{'eng' : 'May', 'transcription' : '[мэй]', 'rus' : 'май'},
{'eng' : 'June', 'transcription' : '[джу:н]', 'rus' : 'июнь'},
{'eng' : 'July', 'transcription' : '[джулAй]', 'rus' : 'июль'},
{'eng' : 'August', 'transcription' : '[O:гэст]', 'rus' : 'август'},
{'eng' : 'September', 'transcription' : '[сэптЭмбэр]', 'rus' : 'сентябрь'},
{'eng' : 'October', 'transcription' : '[октOубэр]', 'rus' : 'октябрь'},
{'eng' : 'November', 'transcription' : '[ноувЭмбэр]', 'rus' : 'ноябрь'},
{'eng' : 'December', 'transcription' : '[дисЭмбэр]', 'rus' : 'декабрь'},
{'eng' : 'season', 'transcription' : '[сИ:зэн]', 'rus' : 'время года; сезон'},
{'eng' : 'spring', 'transcription' : '[спринг]', 'rus' : 'весна'},
{'eng' : 'summer', 'transcription' : '[сAмэр]', 'rus' : 'лето'},
{'eng' : 'autumn', 'transcription' : '[O:тэм]', 'rus' : 'осень'},
{'eng' : 'winter', 'transcription' : '[уИнтэр]', 'rus' : 'зима'},
{'eng' : 'holiday', 'transcription' : '[хOлидэй]', 'rus' : 'праздник; отпуск; каникулы'},
{'eng' : 'Christmas', 'transcription' : '[крИсмэс]', 'rus' : 'Рождество'},
{'eng' : 'Easter', 'transcription' : '[И:стэр]', 'rus' : 'Пасха'},
{'eng' : 'birthday', 'transcription' : '[бё:рсдэй]', 'rus' : 'день рождения'},
{'eng' : 'form', 'transcription' : '[фо:рм]', 'rus' : 'анкета; форма; бланк; класс; формировать, образовывать'},
{'eng' : 'name', 'transcription' : '[нэйм]', 'rus' : 'имя, фамилия; название; называть'},
{'eng' : 'first name', 'transcription' : '[фё:рст нэйм]', 'rus' : 'имя'},
{'eng' : 'surname', 'transcription' : '[сЁ:нэйм]', 'rus' : 'фамилия'},
{'eng' : 'maiden name', 'transcription' : '[мЭйдэн нэйм]', 'rus' : 'девичья фамилия'},
{'eng' : 'birth date', 'transcription' : '[бё:рс дэйт]', 'rus' : 'дата рождения'},
{'eng' : 'place of birth', 'transcription' : '[плэйс ов бё:рс]', 'rus' : 'место рождения'},
{'eng' : 'address', 'transcription' : '[эдрЭс]', 'rus' : 'адрес'},
{'eng' : 'marital status', 'transcription' : '[мЭритэл стЭйтэс]', 'rus' : 'семейное положение'},
{'eng' : 'single', 'transcription' : '[сингл]', 'rus' : 'холостой, незамужняя; один(окий); в один конец (о билете)'},
{'eng' : 'married', 'transcription' : '[мЭрид]', 'rus' : 'женатый/замужняя'},
{'eng' : 'divorced', 'transcription' : '[дивО:рст]', 'rus' : 'разведенный'},
{'eng' : 'widowed', 'transcription' : '[уидоуд]', 'rus' : 'овдовевший'},
{'eng' : 'thing', 'transcription' : '[синг]', 'rus' : 'вещь'},
{'eng' : 'pen', 'transcription' : '[пэн]', 'rus' : 'ручка'},
{'eng' : 'pencil', 'transcription' : '[пЭнсил]', 'rus' : 'карандаш'},
{'eng' : 'book', 'transcription' : '[бук]', 'rus' : 'книга'},
{'eng' : 'copybook', 'transcription' : '[кОпибук]', 'rus' : 'тетрадь'},
{'eng' : 'notebook', 'transcription' : '[нОутбук]', 'rus' : 'блокнот'},
{'eng' : 'note', 'transcription' : '[нОут]', 'rus' : 'записка, запись'},
{'eng' : 'dictionary', 'transcription' : '[дИкшэнэри]', 'rus' : 'словарь'},
{'eng' : 'letter', 'transcription' : '[лЭтэр]', 'rus' : 'письмо; буква'},
{'eng' : 'envelope', 'transcription' : '[Энвилоуп]', 'rus' : 'конверт'},
{'eng' : 'paper', 'transcription' : '[пЭйпэр]', 'rus' : 'бумага'},
{'eng' : 'newspaper', 'transcription' : '[нъЮ:зпэйпер]', 'rus' : 'газета'},
{'eng' : 'magazine', 'transcription' : '[мэгэзИ:н]', 'rus' : 'журнал'},
{'eng' : '(tele)phone', 'transcription' : '[(тЭли)фОун]', 'rus' : 'телефон; разговаривать по телефону'},
{'eng' : 'clock', 'transcription' : '[клок]', 'rus' : 'часы'},
{'eng' : 'comb', 'transcription' : '[коум]', 'rus' : 'расчёска; расчесывать'},
{'eng' : 'TV(-set)', 'transcription' : '[тИви(сэт)]', 'rus' : 'телевизор'},
{'eng' : 'iron', 'transcription' : '[Aйрон]', 'rus' : 'утюг; железо; гладить (утюгом)'},
{'eng' : 'soap', 'transcription' : '[сOуп]', 'rus' : 'мыло; намыливать'},
{'eng' : 'radio', 'transcription' : '[рЭйдиоу]', 'rus' : 'радио'},
{'eng' : 'bag', 'transcription' : '[бэг]', 'rus' : 'сумка'},
{'eng' : 'backpack', 'transcription' : '[бЭкпэк]', 'rus' : 'рюкзак'},
{'eng' : 'map', 'transcription' : '[мэп]', 'rus' : 'карта (географическая)'},
{'eng' : 'card', 'transcription' : '[ка:рд]', 'rus' : 'открытка; карта (игральная); карточка'},
{'eng' : 'suitcase', 'transcription' : '[сУткэйс]', 'rus' : 'чемодан'},
{'eng' : 'present', 'transcription' : '[прэзнт]', 'rus' : 'подарок'},
{'eng' : 'camera', 'transcription' : '[кЭмэрэ]', 'rus' : 'фотоаппарат; видеокамера'},
{'eng' : 'vase', 'transcription' : '[ва:з]', 'rus' : 'ваза'},
{'eng' : 'handkerchief', 'transcription' : '[хЭнкёчиф]', 'rus' : 'носовой платок'},
{'eng' : 'ball', 'transcription' : '[бо:л]', 'rus' : 'мяч'},
{'eng' : 'balloon', 'transcription' : '[бэлу:н]', 'rus' : 'воздушный шар(ик)'},
{'eng' : 'toy', 'transcription' : '[той]', 'rus' : 'игрушка'},
{'eng' : 'ticket', 'transcription' : '[тикит]', 'rus' : 'билет'},
{'eng' : 'luggage', 'transcription' : '[лAгидж]', 'rus' : 'багаж'},
{'eng' : 'battery', 'transcription' : '[бЭтэри]', 'rus' : 'батарейка, аккумулятор'},
{'eng' : 'bucket', 'transcription' : '[бAкит]', 'rus' : 'ведро'},
{'eng' : 'rope', 'transcription' : '[рOуп]', 'rus' : 'веревка'},
{'eng' : 'board', 'transcription' : '[бо:рд]', 'rus' : 'доска; борт; совет (правление)'},
{'eng' : 'calendar', 'transcription' : '[кЭлиндэр]', 'rus' : 'календарь'},
{'eng' : 'laptop', 'transcription' : '[лЭптоп]', 'rus' : 'ноутбук'},
{'eng' : 'brush', 'transcription' : '[браш]', 'rus' : 'щетка; кисть, кисточка; чистить щеткой'},
{'eng' : 'keyboard', 'transcription' : '[кИ:бо:рд]', 'rus' : 'клавиатура'},
{'eng' : 'key', 'transcription' : '[ки:]', 'rus' : 'ключ; клавиша'},
{'eng' : 'wheel', 'transcription' : '[уИ:л]', 'rus' : 'колесо'},
{'eng' : 'steering wheel', 'transcription' : '[стИринг уИ:л]', 'rus' : 'руль'},
{'eng' : 'trunk', 'transcription' : '[транк]', 'rus' : 'багажник; ствол; хобот'},
{'eng' : 'gas(oline)', 'transcription' : '[гЭс(олин)]', 'rus' : 'бензин'},
{'eng' : 'purse', 'transcription' : '[пё:рс]', 'rus' : 'дамская сумка; кошелек'},
{'eng' : 'wallet', 'transcription' : '[уОлит]', 'rus' : 'бумажник'},
{'eng' : 'lamp', 'transcription' : '[лЭмп]', 'rus' : 'лампа'},
{'eng' : 'ruler', 'transcription' : '[рУ:лэр]', 'rus' : 'линейка; правитель'},
{'eng' : 'shovel', 'transcription' : '[шАвэл]', 'rus' : 'лопата; рыть'},
{'eng' : 'machine', 'transcription' : '[мэшИ:н]', 'rus' : 'машина; механизм; аппарат; станок'},
{'eng' : 'hammer', 'transcription' : '[хЭмэр]', 'rus' : 'молоток; вбивать молотком'},
{'eng' : 'scissors', 'transcription' : '[сИзэрз]', 'rus' : 'ножницы'},
{'eng' : 'glasses', 'transcription' : '[глА:сиз]', 'rus' : 'очки'},
{'eng' : 'package', 'transcription' : '[пЭкидж]', 'rus' : 'посылка; упаковка'},
{'eng' : 'stick', 'transcription' : '[стик]', 'rus' : 'палка; придерживаться; втыкать'},
{'eng' : 'glue', 'transcription' : '[глу:]', 'rus' : 'клей; приклеивать'},
{'eng' : 'gift', 'transcription' : '[гифт]', 'rus' : 'подарок; дар'},
{'eng' : 'towel', 'transcription' : '[тАуэл]', 'rus' : 'полотенце'},
{'eng' : 'mail', 'transcription' : '[мэйл]', 'rus' : 'почта (корреспонденция); отправлять по почте'},
{'eng' : 'wire', 'transcription' : '[уАйэр]', 'rus' : 'проволока; провод'},
{'eng' : 'page', 'transcription' : '[пэйдж]', 'rus' : 'страница'},
{'eng' : 'torch', 'transcription' : '[то:рч]', 'rus' : 'карманный фонарь; горелка; факел'},
{'eng' : 'box', 'transcription' : '[бокс]', 'rus' : 'коробка, ящик; боксировать'},
{'eng' : 'blanket', 'transcription' : '[блЭнкит]', 'rus' : 'одеяло'},
{'eng' : 'sheet', 'transcription' : '[ши:т]', 'rus' : 'простыня; лист(ок)'},
{'eng' : 'pillow', 'transcription' : '[пИлоу]', 'rus' : 'подушка'},
{'eng' : 'clothes', 'transcription' : '[клОуз]', 'rus' : 'одежда'},
{'eng' : 'shoes', 'transcription' : '[шу:з]', 'rus' : 'обувь'},
{'eng' : 'boot', 'transcription' : '[бу:т]', 'rus' : 'ботинок; сапог'},
{'eng' : 'sneakers', 'transcription' : '[снИ:кэрз]', 'rus' : 'кроссовки'},
{'eng' : 'coat', 'transcription' : '[коут]', 'rus' : 'пальто'},
{'eng' : 'dress', 'transcription' : '[дрэс]', 'rus' : 'платье; одевать(ся)'},
{'eng' : 'suit', 'transcription' : '[съют]', 'rus' : 'костюм; иск; подходить, быть к лицу, соответствовать'},
{'eng' : 'shirt', 'transcription' : '[шё:рт]', 'rus' : 'рубашка'},
{'eng' : 'blouse', 'transcription' : '[блАуз]', 'rus' : 'блузка'},
{'eng' : 'skirt', 'transcription' : '[скё:рт]', 'rus' : 'юбка'},
{'eng' : 'glove', 'transcription' : '[глав]', 'rus' : 'перчатка'},
{'eng' : 'mitten', 'transcription' : '[мИтэн]', 'rus' : 'варежка'},
{'eng' : 'hat', 'transcription' : '[хэт]', 'rus' : 'шляпа'},
{'eng' : 'cap', 'transcription' : '[кэп]', 'rus' : 'шапка; кепка; колпачок'},
{'eng' : 'jacket', 'transcription' : '[джЭкит]', 'rus' : 'пиджак; куртка'},
{'eng' : 'cardigan', 'transcription' : '[кА:рдигэн]', 'rus' : 'кофта'},
{'eng' : 'scarf', 'transcription' : '[ска:рф]', 'rus' : 'шарф'},
{'eng' : 'sock', 'transcription' : '[сок]', 'rus' : 'носок'},
{'eng' : 'sweater', 'transcription' : '[суэтэр]', 'rus' : 'свитер'},
{'eng' : 'T-shirt', 'transcription' : '[тИ:шё:рт]', 'rus' : 'футболка'},
{'eng' : 'tie', 'transcription' : '[тай]', 'rus' : 'галстук; привязывать'},
{'eng' : 'trousers', 'transcription' : '[трAузэрз]', 'rus' : 'брюки, штаны'},
{'eng' : 'shorts', 'transcription' : '[шо:ртс]', 'rus' : 'шорты'},
{'eng' : 'tights', 'transcription' : '[тайтс]', 'rus' : 'колготки'},
{'eng' : 'stockings', 'transcription' : '[стОкингз]', 'rus' : 'чулки'},
{'eng' : 'jeans', 'transcription' : '[джи:нз]', 'rus' : 'джинсы'},
{'eng' : 'hood', 'transcription' : '[худ]', 'rus' : 'капюшон; капот'},
{'eng' : 'belt', 'transcription' : '[бэлт]', 'rus' : 'ремень, пояс'},
{'eng' : 'underwear', 'transcription' : '[Андэуээ]', 'rus' : 'нижнее белье'},
{'eng' : 'briefs', 'transcription' : '[бри:фс]', 'rus' : 'трусы мужские'},
{'eng' : 'panties', 'transcription' : '[пЭнтиз]', 'rus' : 'трусы женские'},
{'eng' : 'bra', 'transcription' : '[бра:]', 'rus' : 'бюстгальтер'},
{'eng' : 'body', 'transcription' : '[бОди]', 'rus' : 'тело; кузов'},
{'eng' : 'head', 'transcription' : '[хед]', 'rus' : 'голова; глава, руководитель'},
{'eng' : 'face', 'transcription' : '[фэйс]', 'rus' : 'лицо'},
{'eng' : 'forehead', 'transcription' : '[фО:рхед]', 'rus' : 'лоб'},
{'eng' : 'nose', 'transcription' : '[нОуз]', 'rus' : 'нос'},
{'eng' : 'ear', 'transcription' : '[Иэр]', 'rus' : 'ухо; ушко; колос'},
{'eng' : 'mouth', 'transcription' : '[мАус]', 'rus' : 'рот'},
{'eng' : 'throat', 'transcription' : '[срОут]', 'rus' : 'горло'},
{'eng' : 'eye', 'transcription' : '[ай]', 'rus' : 'глаз'},
{'eng' : 'eyebrow', 'transcription' : '[Aйбрау]', 'rus' : 'бровь'},
{'eng' : 'lips', 'transcription' : '[липс]', 'rus' : 'губы'},
{'eng' : 'tooth', 'transcription' : '[ту:с]', 'rus' : 'зуб'},
{'eng' : 'hair', 'transcription' : '[хЭэр]', 'rus' : 'волос(ы)'},
{'eng' : 'mustache', 'transcription' : '[мэстА:ш]', 'rus' : 'усы'},
{'eng' : 'cheek', 'transcription' : '[чи:к]', 'rus' : 'щека; наглость, нахальство'},
{'eng' : 'chin', 'transcription' : '[чин]', 'rus' : 'подбородок'},
{'eng' : 'neck', 'transcription' : '[нек]', 'rus' : 'шея'},
{'eng' : 'shoulder', 'transcription' : '[шОулдэр]', 'rus' : 'плечо'},
{'eng' : 'chest', 'transcription' : '[чест]', 'rus' : 'грудь'},
{'eng' : 'heart', 'transcription' : '[ха:рт]', 'rus' : 'сердце'},
{'eng' : 'stomach', 'transcription' : '[стАмэк]', 'rus' : 'желудок; живот'},
{'eng' : 'back', 'transcription' : '[бЭк]', 'rus' : 'спина; назад'},
{'eng' : 'wrist', 'transcription' : '[рист]', 'rus' : 'запястье'},
{'eng' : 'hand', 'transcription' : '[хЭнд]', 'rus' : 'рука, кисть (руки)'},
{'eng' : 'finger', 'transcription' : '[фИнгэр]', 'rus' : 'палец (руки)'},
{'eng' : 'nail', 'transcription' : '[нэйл]', 'rus' : 'ноготь; гвоздь; прибивать'},
{'eng' : 'elbow', 'transcription' : '[Элбоу]', 'rus' : 'локоть'},
{'eng' : 'leg', 'transcription' : '[лэг]', 'rus' : 'нога; ножка'},
{'eng' : 'knee', 'transcription' : '[ни:]', 'rus' : 'колено'},
{'eng' : 'foot', 'transcription' : '[фут]', 'rus' : 'нога, ступня; подножие'},
{'eng' : 'heel', 'transcription' : '[хи:л]', 'rus' : 'пятка; каблук'},
{'eng' : 'toe', 'transcription' : '[тОу]', 'rus' : 'палец (ноги)'},
{'eng' : 'beard', 'transcription' : '[бИэрд]', 'rus' : 'борода'},
{'eng' : 'bone', 'transcription' : '[бОун]', 'rus' : 'кость'},
{'eng' : 'health', 'transcription' : '[хэлс]', 'rus' : 'здоровье'},
{'eng' : 'healthy', 'transcription' : '[хЭлси]', 'rus' : 'здоровый'},
{'eng' : 'sick', 'transcription' : '[сик]', 'rus' : 'больной'},
{'eng' : 'sickness', 'transcription' : '[сИкнис]', 'rus' : 'болезнь'},
{'eng' : 'fever', 'transcription' : '[фИ:вэр]', 'rus' : 'жар, (высокая) температура'},
{'eng' : 'cough', 'transcription' : '[коф]', 'rus' : 'кашель; кашлять'},
{'eng' : 'running nose', 'transcription' : '[рАнинг нОуз]', 'rus' : 'насморк'},
{'eng' : 'sneeze', 'transcription' : '[сни:з]', 'rus' : 'чихать'},
{'eng' : 'pain', 'transcription' : '[пэйн]', 'rus' : 'боль'},
{'eng' : 'headache', 'transcription' : '[хЕдэйк]', 'rus' : 'головная боль'},
{'eng' : 'flu', 'transcription' : '[флу:]', 'rus' : 'грипп'},
{'eng' : 'bruise', 'transcription' : '[бру:з]', 'rus' : 'синяк, ушиб; ушибить'},
{'eng' : 'event', 'transcription' : '[ивЭнт]', 'rus' : 'событие'},
{'eng' : 'birth', 'transcription' : '[бё:рс]', 'rus' : 'рождение'},
{'eng' : 'game', 'transcription' : '[гейм]', 'rus' : 'игра'},
{'eng' : 'lesson', 'transcription' : '[лэсн]', 'rus' : 'урок'},
{'eng' : 'vacation', 'transcription' : '[вэйкЭйшэн]', 'rus' : 'отпуск, каникулы'},
{'eng' : 'party', 'transcription' : '[пА:рти]', 'rus' : 'вечеринка'},
{'eng' : 'meeting', 'transcription' : '[мИ:тинг]', 'rus' : 'встреча; собрание'},
{'eng' : 'wedding', 'transcription' : '[уЭдинг]', 'rus' : 'свадьба'},
{'eng' : 'negotiation', 'transcription' : '[нигоушиЭйшэн]', 'rus' : 'переговоры'},
{'eng' : 'trip', 'transcription' : '[трип]', 'rus' : 'поездка, путешествие'},
{'eng' : 'death', 'transcription' : '[дэс]', 'rus' : 'смерть'},
{'eng' : 'weather', 'transcription' : '[уЭзэр]', 'rus' : 'погода'},
{'eng' : 'sun', 'transcription' : '[сан]', 'rus' : 'солнце'},
{'eng' : 'moon', 'transcription' : '[му:н]', 'rus' : 'луна'},
{'eng' : 'wind', 'transcription' : '[уинд]', 'rus' : 'ветер'},
{'eng' : 'fog', 'transcription' : '[фог]', 'rus' : 'туман'},
{'eng' : 'rain', 'transcription' : '[рэйн]', 'rus' : 'дождь'},
{'eng' : 'snow', 'transcription' : '[снOу]', 'rus' : 'снег'},
{'eng' : 'sky', 'transcription' : '[скай]', 'rus' : 'небо'},
{'eng' : 'cloud', 'transcription' : '[клАуд]', 'rus' : 'облако'},
{'eng' : 'air', 'transcription' : '[Ээр]', 'rus' : 'воздух'},
{'eng' : 'temperature', 'transcription' : '[тЭмпрэчэ]', 'rus' : 'температура'},
{'eng' : 'degree', 'transcription' : '[дигрИ:]', 'rus' : 'градус; степень'},
{'eng' : 'art', 'transcription' : '[а:рт]', 'rus' : 'искусство'},
{'eng' : 'music', 'transcription' : '[мъЮзик]', 'rus' : 'музыка'},
{'eng' : 'song', 'transcription' : '[сонг]', 'rus' : 'песня'},
{'eng' : 'literature', 'transcription' : '[лИтрэчэ]', 'rus' : 'литература'},
{'eng' : 'story', 'transcription' : '[стОри]', 'rus' : 'рассказ, история'},
{'eng' : 'movie', 'transcription' : '[мУви]', 'rus' : 'кино(фильм)'},
{'eng' : 'film', 'transcription' : '[филм]', 'rus' : 'фильм; пленка'},
{'eng' : 'sculpture', 'transcription' : '[скАлпчэ]', 'rus' : 'скульптура; статуя'},
{'eng' : 'picture', 'transcription' : '[пИкчэр]', 'rus' : 'картина; фотография'},
{'eng' : 'photo', 'transcription' : '[фОутоу]', 'rus' : 'фото'},
{'eng' : 'advertising', 'transcription' : '[эдвэртАйзинг]', 'rus' : 'реклам'},
{'eng' : 'purchase', 'transcription' : '[пЁ:рчэс]', 'rus' : 'покупка, приобретение; покупать, приобретат'},
{'eng' : 'size', 'transcription' : '[сайз]', 'rus' : 'размер'},
{'eng' : 'price', 'transcription' : '[прайc]', 'rus' : 'цена'},
{'eng' : 'money', 'transcription' : '[мAни]', 'rus' : 'деньги'},
{'eng' : 'cash', 'transcription' : '[кэш]', 'rus' : 'наличные (деньги)'},
{'eng' : 'discount', 'transcription' : '[дискАунт]', 'rus' : 'скидка'},
{'eng' : 'account', 'transcription' : '[экАунт]', 'rus' : 'счет (банковский)'},
{'eng' : 'bill', 'transcription' : '[бил]', 'rus' : 'счёт'},
{'eng' : 'tip', 'transcription' : '[тип]', 'rus' : 'чаевые; кончик, верхушка; совет'},
{'eng' : 'measure', 'transcription' : '[мЭжэ]', 'rus' : 'измерение; мера; измерять'},
{'eng' : 'distance', 'transcription' : '[дИстэнс]', 'rus' : 'расстояние; дистанция'},
{'eng' : 'length', 'transcription' : '[лэнгс]', 'rus' : 'длина'},
{'eng' : 'height', 'transcription' : '[хайт]', 'rus' : 'высота'},
{'eng' : 'depth', 'transcription' : '[дэпс]', 'rus' : 'глубина'},
{'eng' : 'strength', 'transcription' : '[стрэнгс]', 'rus' : 'сила; прочность'},
{'eng' : 'speed', 'transcription' : '[спи:д]', 'rus' : 'скорость'},
{'eng' : 'kilometer', 'transcription' : '[кИлэми:тэр]', 'rus' : 'километр'},
{'eng' : 'kilogram', 'transcription' : '[кИлэгрэм]', 'rus' : 'килограмм'},
{'eng' : 'pound', 'transcription' : '[пАунд]', 'rus' : 'фунт'},
{'eng' : 'feeling', 'transcription' : '[фИ:линг]', 'rus' : 'чувство'},
{'eng' : 'fun', 'transcription' : '[фан]', 'rus' : 'веселье'},
{'eng' : 'joy', 'transcription' : '[джой]', 'rus' : 'радость'},
{'eng' : 'fear', 'transcription' : '[фИэр]', 'rus' : 'страх; бояться'},
{'eng' : 'sadness', 'transcription' : '[сЭднис]', 'rus' : 'печаль'},
{'eng' : 'passion', 'transcription' : '[пэшн]', 'rus' : 'страсть, страстность'},
{'eng' : 'pleasure', 'transcription' : '[плЭжэ]', 'rus' : 'удовольствие'},
{'eng' : 'happiness', 'transcription' : '[хЭпинис]', 'rus' : 'счастье'},
{'eng' : 'peace', 'transcription' : '[пи:с]', 'rus' : 'мир (покой)'},
{'eng' : 'love', 'transcription' : '[лав]', 'rus' : 'любовь; любить'},
{'eng' : 'hate', 'transcription' : '[хэйт]', 'rus' : 'ненависть; ненавидеть'},
{'eng' : 'world', 'transcription' : '[уО:рлд]', 'rus' : 'мир (планета)'},
{'eng' : 'soul', 'transcription' : '[сОул]', 'rus' : 'душа'},
{'eng' : 'life', 'transcription' : '[лайф]', 'rus' : 'жизнь'},
{'eng' : 'knowledge', 'transcription' : '[нОлидж]', 'rus' : 'знание'},
{'eng' : 'task', 'transcription' : '[та:ск]', 'rus' : 'задача, задание'},
{'eng' : 'exercise', 'transcription' : '[Эксэрсайз]', 'rus' : 'упражнение; упражняться; осуществлять'},
{'eng' : 'luck', 'transcription' : '[лак]', 'rus' : 'удача'},
{'eng' : 'problem', 'transcription' : '[прOблем]', 'rus' : 'проблема'},
{'eng' : 'opportunity', 'transcription' : '[опэртъЮ:нэти]', 'rus' : '(благоприятная) возможность'},
{'eng' : 'ability', 'transcription' : '[эбИлэти]', 'rus' : 'способность'},
{'eng' : 'beauty', 'transcription' : '[бъЮ:ти]', 'rus' : 'красота; красавица'},
{'eng' : 'danger', 'transcription' : '[дЭйнджэр]', 'rus' : 'опасность'},
{'eng' : 'experience', 'transcription' : '[икспИэриэнс]', 'rus' : 'опыт, переживание'},
{'eng' : 'memory', 'transcription' : '[мЭмэри]', 'rus' : 'память; воспоминание'},
{'eng' : 'benefit', 'transcription' : '[бЭнэфит]', 'rus' : 'польза, выгода; приносить (извлекать) пользу'},
{'eng' : 'advantage', 'transcription' : '[эдвЭнтидж]', 'rus' : 'преимущество'},
{'eng' : 'profit', 'transcription' : '[прОфит]', 'rus' : 'прибыль, доход; польза, выгода; извлекать пользу, выгоду'},
{'eng' : 'habit', 'transcription' : '[хЭбит]', 'rus' : 'привычка'},
{'eng' : 'reason', 'transcription' : '[рИ:зэн]', 'rus' : 'причина; размышлять'},
{'eng' : 'consequence', 'transcription' : '[кОнсэкуэнс]', 'rus' : '(по)следствие'},
{'eng' : 'meaning', 'transcription' : '[мИ:нинг]', 'rus' : 'значение, смысл'},
{'eng' : 'means', 'transcription' : '[мИ:нз]', 'rus' : 'средство, способ'},
{'eng' : 'effort', 'transcription' : '[Эфэрт]', 'rus' : 'усилие'},
{'eng' : 'success', 'transcription' : '[саксЭс]', 'rus' : 'успех; успешный человек'},
{'eng' : 'goal', 'transcription' : '[гОул]', 'rus' : 'цель; гол'},
{'eng' : 'miracle', 'transcription' : '[мИрэкл]', 'rus' : 'чудо'},
{'eng' : 'science', 'transcription' : '[сАйэнс]', 'rus' : 'наука'},
{'eng' : 'language', 'transcription' : '[лЭнгуидж]', 'rus' : 'язык'},
{'eng' : 'word', 'transcription' : '[уо:рд]', 'rus' : 'слово'},
{'eng' : 'fire', 'transcription' : '[фАйэр]', 'rus' : 'огонь; пожар; стрелять'},
{'eng' : 'case', 'transcription' : '[кейс]', 'rus' : 'случай; дело; чехол'},
{'eng' : 'circumstance', 'transcription' : '[сЁ:ркэмстэнс]', 'rus' : 'обстоятельство'},
{'eng' : 'thought', 'transcription' : '[cо:т]', 'rus' : 'мысль'},
{'eng' : 'choice', 'transcription' : '[чойс]', 'rus' : 'выбор'},
{'eng' : 'permit', 'transcription' : '[пёрмИт]', 'rus' : 'разрешение; разрешать'},
{'eng' : 'delivery', 'transcription' : '[дилИвэри]', 'rus' : 'доставка; поставка'},
{'eng' : 'achievement', 'transcription' : '[эчИвмент]', 'rus' : 'достижение'},
{'eng' : 'duty', 'transcription' : '[дъЮ:ти]', 'rus' : 'обязанность; дежурный'},
{'eng' : 'delay', 'transcription' : '[дилЭй]', 'rus' : 'задержка, промедление, отсрочка; откладывать, задерживать, промедлять'},
{'eng' : 'relationship', 'transcription' : '[рилЭйшэншип]', 'rus' : 'отношение'},
{'eng' : 'mark', 'transcription' : '[ма:рк]', 'rus' : 'оценка, отметка, знак; отметить'},
{'eng' : 'mistake', 'transcription' : '[мистЭйк]', 'rus' : 'ошибка'},
{'eng' : 'behavior', 'transcription' : '[бихЭйвъэр]', 'rus' : 'поведение'},
{'eng' : 'invitation', 'transcription' : '[инвитЭйшн]', 'rus' : 'приглашение'},
{'eng' : 'development', 'transcription' : '[дивЭлэпмэнт]', 'rus' : 'развитие'},
{'eng' : 'decision', 'transcription' : '[дисИ:жн]', 'rus' : 'решение, принятие решения'},
{'eng' : 'solution', 'transcription' : '[сэлЮ:шн]', 'rus' : 'решение; раствор'},
{'eng' : 'advice', 'transcription' : '[эдвАйс]', 'rus' : 'совет'},
{'eng' : 'agreement', 'transcription' : '[эгрИ:мэнт]', 'rus' : 'соглашение; согласие; договор'},
{'eng' : 'list', 'transcription' : '[лист]', 'rus' : 'список; перечислять'},
{'eng' : 'argument', 'transcription' : '[А:ргъюмэнт]', 'rus' : 'спор; аргумент'},
{'eng' : 'test', 'transcription' : '[тэст]', 'rus' : 'тест, испытание; тестировать, испытывать'},
{'eng' : 'step', 'transcription' : '[стэп]', 'rus' : 'шаг; ступать'},
{'eng' : 'piece', 'transcription' : '[пи:с]', 'rus' : 'кусок; часть; пьеса'},
{'eng' : 'area', 'transcription' : '[Ээриэ]', 'rus' : 'область, сфера, район; площадь (фигуры)'},
{'eng' : 'pair', 'transcription' : '[пЭэр]', 'rus' : 'пара'},
{'eng' : 'couple', 'transcription' : '[капл]', 'rus' : 'пара; чета'},
{'eng' : 'surface', 'transcription' : '[сЁ:рфис]', 'rus' : 'поверхность; всплывать'},
{'eng' : 'mess', 'transcription' : '[мэс]', 'rus' : 'беспорядок; привести в беспорядок'},
{'eng' : 'question', 'transcription' : '[куЭсчэн]', 'rus' : 'вопрос'},
{'eng' : 'what', 'transcription' : '[уот]', 'rus' : 'что; какой'},
{'eng' : 'who', 'transcription' : '[ху:]', 'rus' : 'кто'},
{'eng' : 'where', 'transcription' : '[уЭэ]', 'rus' : 'где; куда'},
{'eng' : 'how', 'transcription' : '[хАу]', 'rus' : 'как'},
{'eng' : 'why', 'transcription' : '[уай]', 'rus' : 'почему, зачем'},
{'eng' : 'when', 'transcription' : '[уэн]', 'rus' : 'когда'},
{'eng' : 'how many', 'transcription' : '[хАу мЭни]', 'rus' : 'сколько (+ слово во множественном числе)'},
{'eng' : 'how much', 'transcription' : '[хАу мач]', 'rus' : 'сколько (+ слово в единственном числе)'},
{'eng' : 'I', 'transcription' : '[ай]', 'rus' : 'я'},
{'eng' : 'you', 'transcription' : '[ю:]', 'rus' : 'ты; вы; Вы'},
{'eng' : 'he', 'transcription' : '[хи:]', 'rus' : 'он'},
{'eng' : 'she', 'transcription' : '[ши:]', 'rus' : 'она;'},
{'eng' : 'it', 'transcription' : '[ит]', 'rus' : 'оно'},
{'eng' : 'we', 'transcription' : '[уи:]', 'rus' : 'мы'},
{'eng' : 'they', 'transcription' : '[зэй]', 'rus' : 'они'},
{'eng' : 'my', 'transcription' : '[май]', 'rus' : 'мой'},
{'eng' : 'your', 'transcription' : '[ё:]', 'rus' : 'твой; ваш'},
{'eng' : 'his', 'transcription' : '[хиз]', 'rus' : 'его (одуш.)'},
{'eng' : 'her', 'transcription' : '[хё:]', 'rus' : 'её'},
{'eng' : 'its', 'transcription' : '[итс]', 'rus' : 'его (неодуш.)'},
{'eng' : 'our', 'transcription' : '[Aуэ]', 'rus' : 'наш'},
{'eng' : 'their', 'transcription' : '[зЭэ]', 'rus' : 'их'},
{'eng' : 'from', 'transcription' : '[фром]', 'rus' : 'из'},
{'eng' : 'of', 'transcription' : '[ов]', 'rus' : 'передает род. падеж'},
{'eng' : 'to', 'transcription' : '[ту]', 'rus' : 'к; в (куда)'},
{'eng' : 'in', 'transcription' : '[ин]', 'rus' : 'в (где)'},
{'eng' : 'on', 'transcription' : '[он]', 'rus' : 'на'},
{'eng' : 'under', 'transcription' : '[Aндэр]', 'rus' : 'под'},
{'eng' : 'behind', 'transcription' : '[бихAйнд]', 'rus' : 'позади'},
{'eng' : 'with', 'transcription' : '[уиз]', 'rus' : 'с'},
{'eng' : 'without', 'transcription' : '[уизAут]', 'rus' : 'без'},
{'eng' : 'in front of', 'transcription' : '[ин франт ов]', 'rus' : 'перед'},
{'eng' : 'before', 'transcription' : '[бифO:р]', 'rus' : 'до'},
{'eng' : 'after', 'transcription' : '[Aфтэр]', 'rus' : 'после'},
{'eng' : 'between', 'transcription' : '[битуИ:н]', 'rus' : 'между'},
{'eng' : 'near', 'transcription' : '[нИэ]', 'rus' : 'возле, около; близко'},
{'eng' : 'for', 'transcription' : '[фо:р]', 'rus' : 'для; в течение; на (такое-то время)'},
{'eng' : 'since', 'transcription' : '[синс]', 'rus' : 'с (такого-то времени и поныне)'},
{'eng' : 'during', 'transcription' : '[дъЮринг]', 'rus' : 'во время'},
{'eng' : 'around', 'transcription' : '[эрAунд]', 'rus' : 'вокруг'},
{'eng' : 'because of', 'transcription' : '[бикО:з ов]', 'rus' : 'из-за'},
{'eng' : 'about', 'transcription' : '[эбАут]', 'rus' : 'о; около, приблизительно'},
{'eng' : 'against', 'transcription' : '[эгЭйнст]', 'rus' : 'против'},
{'eng' : 'among', 'transcription' : '[эмАнг]', 'rus' : 'среди'},
{'eng' : 'through', 'transcription' : '[сру:]', 'rus' : 'через'},
{'eng' : 'per', 'transcription' : '[пё:р]', 'rus' : '(километров) в (час)'},
{'eng' : 'above', 'transcription' : '[эбАв]', 'rus' : 'над, выше'},
{'eng' : 'below', 'transcription' : '[билОу]', 'rus' : 'под, ниже'},
{'eng' : 'number', 'transcription' : '[нАмбэр]', 'rus' : 'число; количество; номер'},
{'eng' : 'zero', 'transcription' : '[зИэроу]', 'rus' : 'ноль'},
{'eng' : 'one', 'transcription' : '[уан]', 'rus' : 'один'},
{'eng' : 'two', 'transcription' : '[ту:]', 'rus' : 'два'},
{'eng' : 'three', 'transcription' : '[сри:]', 'rus' : 'три'},
{'eng' : 'four', 'transcription' : '[фо:р]', 'rus' : 'четыре'},
{'eng' : 'five', 'transcription' : '[файв]', 'rus' : 'пять'},
{'eng' : 'six', 'transcription' : '[сикс]', 'rus' : 'шесть'},
{'eng' : 'seven', 'transcription' : '[сЭвэн]', 'rus' : 'семь'},
{'eng' : 'eight', 'transcription' : '[эйт]', 'rus' : 'восемь'},
{'eng' : 'nine', 'transcription' : '[найн]', 'rus' : 'девять'},
{'eng' : 'ten', 'transcription' : '[тэн]', 'rus' : 'десять'},
{'eng' : 'eleven', 'transcription' : '[илЭвн]', 'rus' : 'одиннадцать'},
{'eng' : 'twelve', 'transcription' : '[туэлв]', 'rus' : 'двенадцать'},
{'eng' : 'thirteen', 'transcription' : '[сЁ:ртИ:н]', 'rus' : 'тринадцать'},
{'eng' : 'fourteen', 'transcription' : '[фO:ртИ:н]', 'rus' : 'четырнадцать'},
{'eng' : 'fifteen', 'transcription' : '[фИфтИ:н[', 'rus' : 'пятнадцать'},
{'eng' : 'sixteen', 'transcription' : '[сИкстИ:н]', 'rus' : 'шестнадцать'},
{'eng' : 'seventeen', 'transcription' : '[сЭвэнтИ:н]', 'rus' : 'семнадцать'},
{'eng' : 'eighteen', 'transcription' : '[ЭйтИ:н]', 'rus' : 'восемнадцать'},
{'eng' : 'nineteen', 'transcription' : '[нAйнтИ:н]', 'rus' : 'девятнадцать'},
{'eng' : 'twenty', 'transcription' : '[туЭнти]', 'rus' : 'двадцать'},
{'eng' : 'thirty', 'transcription' : '[сЁ:ти]', 'rus' : 'тридцать'},
{'eng' : 'forty', 'transcription' : '[фO:рти]', 'rus' : 'сорок '},
{'eng' : 'fifty', 'transcription' : '[фИфти]', 'rus' : 'пятьдесят'},
{'eng' : 'sixty', 'transcription' : '[сИксти]', 'rus' : 'шестьдесят'},
{'eng' : 'seventy', 'transcription' : '[сЭвэнти]', 'rus' : 'семьдесят'},
{'eng' : 'eighty', 'transcription' : '[Эйти]', 'rus' : 'восемьдесят'},
{'eng' : 'ninety', 'transcription' : '[нAйнти]', 'rus' : 'девяносто'},
{'eng' : 'hundred', 'transcription' : '[хАндрид]', 'rus' : 'сто'},
{'eng' : 'thousand', 'transcription' : '[сAузэнд]', 'rus' : 'тысяча'},
{'eng' : 'first', 'transcription' : '[фё:рст]', 'rus' : 'первый; сначала'},
{'eng' : 'second', 'transcription' : '[сЭкэнд]', 'rus' : 'второй; секунда'},
{'eng' : 'third', 'transcription' : '[сё:рд]', 'rus' : 'третий'},
{'eng' : 'fourth', 'transcription' : '[фо:рс]', 'rus' : 'четвертый'},
{'eng' : 'fifth', 'transcription' : '[фифс]', 'rus' : 'пятый'},
{'eng' : 'color', 'transcription' : '[кАлэр]', 'rus' : 'цвет'},
{'eng' : 'black', 'transcription' : '[блэк]', 'rus' : 'чёрный'},
{'eng' : 'blue', 'transcription' : '[блу:]', 'rus' : 'голубой; синий'},
{'eng' : 'brown', 'transcription' : '[брАун]', 'rus' : 'коричневый'},
{'eng' : 'green', 'transcription' : '[гри:н]', 'rus' : 'зелёный'},
{'eng' : 'grey', 'transcription' : '[грэй]', 'rus' : 'серый'},
{'eng' : 'red', 'transcription' : '[рэд]', 'rus' : 'красный'},
{'eng' : 'white', 'transcription' : '[уайт]', 'rus' : 'белый'},
{'eng' : 'yellow', 'transcription' : '[йEлоу]', 'rus' : 'жёлтый'},
{'eng' : 'pink', 'transcription' : '[пинк]', 'rus' : 'розовый'},
{'eng' : 'purple', 'transcription' : '[пё:рпл]', 'rus' : 'фиолетовый; пурпурный'},
{'eng' : 'old', 'transcription' : '[Oулд]', 'rus' : 'старый'},
{'eng' : 'young', 'transcription' : '[янг]', 'rus' : 'молодой'},
{'eng' : 'new', 'transcription' : '[нъю:]', 'rus' : 'новый'},
{'eng' : 'big', 'transcription' : '[биг]', 'rus' : 'большой'},
{'eng' : 'large', 'transcription' : '[ла:рдж]', 'rus' : 'большой, просторный'},
{'eng' : 'huge', 'transcription' : '[хъюдж]', 'rus' : 'огромный'},
{'eng' : 'small', 'transcription' : '[смо:л]', 'rus' : 'маленький'},
{'eng' : 'fat', 'transcription' : '[фэт]', 'rus' : 'толстый, жирный; жир'},
{'eng' : 'slim', 'transcription' : '[слим]', 'rus' : 'тонкий, стройный'},
{'eng' : 'thick', 'transcription' : '[сик]', 'rus' : 'толстый; густой'},
{'eng' : 'thin', 'transcription' : '[син]', 'rus' : 'тонкий'},
{'eng' : 'hungry', 'transcription' : '[хAнгри]', 'rus' : 'голодный'},
{'eng' : 'full', 'transcription' : '[фул]', 'rus' : 'сытый; полный'},
{'eng' : 'good', 'transcription' : '[гуд]', 'rus' : 'хороший; добрый'},
{'eng' : 'excellent', 'transcription' : '[Эксэлэнт]', 'rus' : 'отличный, превосходный, великолепный'},
{'eng' : 'amazing', 'transcription' : '[эмЭйзинг]', 'rus' : 'удивительный'},
{'eng' : 'fine', 'transcription' : '[файн]', 'rus' : 'прекрасный; прекрасно; утонченный; штраф; штрафовать'},
{'eng' : 'bad', 'transcription' : '[бэд]', 'rus' : 'плохой'},
{'eng' : 'terrible', 'transcription' : '[тЭрибл]', 'rus' : 'ужасный'},
{'eng' : 'nasty', 'transcription' : '[нЭсти]', 'rus' : 'противный'},
{'eng' : 'early', 'transcription' : '[\'Ёли]', 'rus' : 'ранний; рано'},
{'eng' : 'late', 'transcription' : '[лэйт]', 'rus' : 'поздний; поздно'},
{'eng' : 'last', 'transcription' : '[ла:ст]', 'rus' : 'последний, прошлый'},
{'eng' : 'next', 'transcription' : '[нэкст]', 'rus' : 'следующий'},
{'eng' : 'free', 'transcription' : '[фри:]', 'rus' : 'свободный; бесплатный'},
{'eng' : 'busy', 'transcription' : '[бИзи]', 'rus' : 'занятый'},
{'eng' : 'hot', 'transcription' : '[хот]', 'rus' : 'жаркий; горячий; острый (по вкусу); жарко; горячо'},
{'eng' : 'warm', 'transcription' : '[уо:рм]', 'rus' : 'тёплый; тепло'},
{'eng' : 'cold', 'transcription' : '[кOулд]', 'rus' : 'холодный; холодно; холод; простуда'},
{'eng' : 'cool', 'transcription' : '[ку:л]', 'rus' : 'прохладный; прохладно; круто; охлаждать(ся)'},
{'eng' : 'spicy', 'transcription' : '[спAйси]', 'rus' : 'острый (по вкусу)'},
{'eng' : 'sharp', 'transcription' : '[ша:рп]', 'rus' : 'острый (не тупой)'},
{'eng' : 'blunt', 'transcription' : '[блант]', 'rus' : 'тупой (нож, человек)'},
{'eng' : 'stupid', 'transcription' : '[ступид]', 'rus' : 'глупый'},
{'eng' : 'clever', 'transcription' : '[клЭвэр]', 'rus' : 'умный'},
{'eng' : 'smart', 'transcription' : '[сма:рт]', 'rus' : 'умный; нарядный'},
{'eng' : 'nice', 'transcription' : '[найс]', 'rus' : 'красивый, хороший, приятный'},
{'eng' : 'beautiful', 'transcription' : '[бъЮ:тэфэл)', 'rus' : 'красивая (о женщине)'},
{'eng' : 'handsome', 'transcription' : '[хЭнсэм]', 'rus' : 'красивый (о мужчине)'},
{'eng' : 'attractive', 'transcription' : '[этрЭктив]', 'rus' : 'привлекательный'},
{'eng' : 'pretty', 'transcription' : '[прИти]', 'rus' : 'симпатичный; довольно'},
{'eng' : 'ugly', 'transcription' : '[Агли]', 'rus' : 'уродливый, безобразный'},
{'eng' : 'high', 'transcription' : '[хай]', 'rus' : 'высокий'},
{'eng' : 'tall', 'transcription' : '[то:л]', 'rus' : 'высокий (о росте)'},
{'eng' : 'short', 'transcription' : '[шо:рт]', 'rus' : 'короткий; низкий (о росте)'},
{'eng' : 'low', 'transcription' : '[лОу]', 'rus' : 'низкий; низко'},
{'eng' : 'long', 'transcription' : '[лонг]', 'rus' : 'длинный; долгий'},
{'eng' : 'heavy', 'transcription' : '[хЭви]', 'rus' : 'тяжёлый'},
{'eng' : 'light', 'transcription' : '[лайт]', 'rus' : 'лёгкий; светлый; свет'},
{'eng' : 'difficult', 'transcription' : '[дИфикалт]', 'rus' : 'трудный, тяжелый'},
{'eng' : 'easy', 'transcription' : '[И:зи]', 'rus' : 'легкий, нетрудный'},
{'eng' : 'simple', 'transcription' : '[симпл]', 'rus' : 'простой'},
{'eng' : 'dark', 'transcription' : '[да:рк]', 'rus' : 'тёмный'},
{'eng' : 'expensive', 'transcription' : '[икспЭнсив]', 'rus' : 'дорогой (по цене)'},
{'eng' : 'dear', 'transcription' : '[дИэр]', 'rus' : 'дорогой, милый'},
{'eng' : 'cheap', 'transcription' : '[чи:п]', 'rus' : 'дешёвый'},
{'eng' : 'poor', 'transcription' : '[пУэр]', 'rus' : 'бедный; плохой'},
{'eng' : 'rich', 'transcription' : '[рич]', 'rus' : 'богатый'},
{'eng' : 'straight', 'transcription' : '[стрэйт]', 'rus' : 'прямой; прямо'},
{'eng' : 'left', 'transcription' : '[лэфт]', 'rus' : 'левый; cлева; налево'},
{'eng' : 'right', 'transcription' : '[райт]', 'rus' : 'правый; правильный; справа; направо; право; прямо (напр., прямо сейчас)'},
{'eng' : 'wrong', 'transcription' : '[ронг]', 'rus' : 'неправильный'},
{'eng' : 'fast', 'transcription' : '[фаст]', 'rus' : 'быстрый, быстро'},
{'eng' : 'quick', 'transcription' : '[куик]', 'rus' : 'быстрый, скорый'},
{'eng' : 'slow', 'transcription' : '[слOу]', 'rus' : 'медленный'},
{'eng' : 'soft', 'transcription' : '[софт]', 'rus' : 'мягкий; нежный'},
{'eng' : 'hard', 'transcription' : '[ха:рд]', 'rus' : 'твёрдый; жесткий; трудный; усердно, упорно'},
{'eng' : 'sad', 'transcription' : '[сэд]', 'rus' : 'печальный'},
{'eng' : 'glad', 'transcription' : '[глэд]', 'rus' : 'радостный'},
{'eng' : 'happy', 'transcription' : '[хЭппи]', 'rus' : 'счастливый'},
{'eng' : 'merry', 'transcription' : '[мЭри]', 'rus' : 'веселый'},
{'eng' : 'kind', 'transcription' : '[кайнд]', 'rus' : 'добрый; вид, тип'},
{'eng' : 'angry', 'transcription' : '[Энгри]', 'rus' : 'сердитый'},
{'eng' : 'evil', 'transcription' : '[И:вэл]', 'rus' : 'злой; зло'},
{'eng' : 'polite', 'transcription' : '[пэлАйт]', 'rus' : 'вежливый'},
{'eng' : 'rude', 'transcription' : '[ру:д]', 'rus' : 'грубый'},
{'eng' : 'gentle', 'transcription' : '[джэнтл]', 'rus' : 'нежный'},
{'eng' : 'brave', 'transcription' : '[брэйв]', 'rus' : 'смелый'},
{'eng' : 'coward', 'transcription' : '[кАуэрд]', 'rus' : 'трусливый; трус'},
{'eng' : 'shy', 'transcription' : '[шай]', 'rus' : 'застенчивый'},
{'eng' : 'hard-working', 'transcription' : '[ха:рд уО:ркинг]', 'rus' : 'трудолюбивый, прилежный'},
{'eng' : 'lazy', 'transcription' : '[лЭйзи]', 'rus' : 'ленивый'},
{'eng' : 'useful', 'transcription' : '[Ю:сфэл]', 'rus' : 'полезный'},
{'eng' : 'useless', 'transcription' : '[Ю:слис]', 'rus' : 'бесполезный'},
{'eng' : 'strong', 'transcription' : '[стронг]', 'rus' : 'сильный; крепкий'},
{'eng' : 'weak', 'transcription' : '[уИ:к]', 'rus' : 'слабый'},
{'eng' : 'loud', 'transcription' : '[лАуд]', 'rus' : 'громкий'},
{'eng' : 'noisy', 'transcription' : '[нОйзи]', 'rus' : 'шумный'},
{'eng' : 'quiet', 'transcription' : '[куАйэт]', 'rus' : 'тихий'},
{'eng' : 'calm', 'transcription' : '[ка:м]', 'rus' : 'спокойный; спокойствие; успокаивать'},
{'eng' : 'narrow', 'transcription' : '[нЭроу]', 'rus' : 'узкий'},
{'eng' : 'wide', 'transcription' : '[уАйд]', 'rus' : 'широкий'},
{'eng' : 'clean', 'transcription' : '[кли:н]', 'rus' : 'чистый; чистить, прибираться'},
{'eng' : 'dirty', 'transcription' : '[дЁ:рти]', 'rus' : 'грязный'},
{'eng' : 'tired', 'transcription' : '[тАйэрд]', 'rus' : 'усталый'},
{'eng' : 'honest', 'transcription' : '[Онист]', 'rus' : 'честный'},
{'eng' : 'comfortable', 'transcription' : '[кАмфэртэбэл]', 'rus' : 'удобный, комфортабельный, уютный'},
{'eng' : 'strange', 'transcription' : '[стрэйндж]', 'rus' : 'странный; чужой; незнакомый'},
{'eng' : 'weird', 'transcription' : '[уИэрд]', 'rus' : 'странный'},
{'eng' : 'own', 'transcription' : '[Оун]', 'rus' : 'собственный; владеть'},
{'eng' : 'tasty', 'transcription' : '[тЭйсти]', 'rus' : 'вкусный'},
{'eng' : 'delicious', 'transcription' : '[дилИшес]', 'rus' : 'очень вкусный'},
{'eng' : 'bitter', 'transcription' : '[бИтэр]', 'rus' : 'горький'},
{'eng' : 'sour', 'transcription' : '[сАуэр]', 'rus' : 'кислый'},
{'eng' : 'salty', 'transcription' : '[сО:лти]', 'rus' : 'соленый'},
{'eng' : 'ready', 'transcription' : '[рЭди]', 'rus' : 'готовый'},
{'eng' : 'careful', 'transcription' : '[кЭэфул]', 'rus' : 'внимательный; осторожный'},
{'eng' : 'main', 'transcription' : '[мэйн]', 'rus' : 'основной, главный'},
{'eng' : 'able', 'transcription' : '[эйбл]', 'rus' : 'способный'},
{'eng' : 'necessary', 'transcription' : '[нЭсэсэри]', 'rus' : 'необходимый'},
{'eng' : 'important', 'transcription' : '[импО:ртэнт]', 'rus' : 'важный'},
{'eng' : 'sure', 'transcription' : '[шУэ]', 'rus' : 'уверенный'},
{'eng' : 'fit', 'transcription' : '[фит]', 'rus' : 'в хорошей форме; подходить, соответствовать'},
{'eng' : 'better', 'transcription' : '[бЭтэр]', 'rus' : 'лучше; более хороший'},
{'eng' : 'best', 'transcription' : '[бэст]', 'rus' : 'лучший'},
{'eng' : 'worse', 'transcription' : '[уо:рс]', 'rus' : 'хуже; более плохой'},
{'eng' : 'worst', 'transcription' : '[уо:рст]', 'rus' : 'худший'},
{'eng' : 'more', 'transcription' : '[мо:р]', 'rus' : 'больше (по количеству); более; еще (больше)'},
{'eng' : 'most', 'transcription' : '[мОуст]', 'rus' : 'наибольший; больше всего; большинство'},
{'eng' : 'less', 'transcription' : '[лэс]', 'rus' : 'меньше (по количеству); менее'},
{'eng' : 'least', 'transcription' : '[ли:ст]', 'rus' : 'наименьший; наименее; меньше всего'},
{'eng' : 'sometimes', 'transcription' : '[сАмтаймз]', 'rus' : 'иногда'},
{'eng' : 'never', 'transcription' : '[нЭвэр]', 'rus' : 'никогда'},
{'eng' : 'seldom', 'transcription' : '[сЭлдом]', 'rus' : 'редко'},
{'eng' : 'usually', 'transcription' : '[Ю:жу:эли]', 'rus' : 'обычно'},
{'eng' : 'often', 'transcription' : '[Оф(т)эн]', 'rus' : 'часто'},
{'eng' : 'always', 'transcription' : '[O:лвэйз]', 'rus' : 'всегда'},
{'eng' : 'soon', 'transcription' : '[су:н]', 'rus' : 'скоро'},
{'eng' : 'recently', 'transcription' : '[рИ:сэнтли]', 'rus' : 'недавно'},
{'eng' : 'well', 'transcription' : '[уЭл]', 'rus' : 'хорошо; колодец'},
{'eng' : 'far', 'transcription' : '[фа:р]', 'rus' : 'далеко'},
{'eng' : 'exactly', 'transcription' : '[игзЭктли]', 'rus' : 'точно'},
{'eng' : 'probably', 'transcription' : '[прOбэбли]', 'rus' : 'вероятно'},
{'eng' : 'maybe', 'transcription' : '[мЭйби]', 'rus' : 'может быть'},
{'eng' : 'perhaps', 'transcription' : '[пёрхЭпс]', 'rus' : 'возможно, может быть'},
{'eng' : 'really', 'transcription' : '[рИэли]', 'rus' : 'действительно, "правда?"'},
{'eng' : 'of course', 'transcription' : '[ов кО:с]', 'rus' : '"конечно!"'},
{'eng' : 'certainly', 'transcription' : '[сЁ:тэнли]', 'rus' : 'конечно, безусловно'},
{'eng' : 'obviously', 'transcription' : '[Обвиэсли]', 'rus' : 'очевидно'},
{'eng' : 'especially', 'transcription' : '[испЭшэли]', 'rus' : 'особенно'},
{'eng' : 'yes', 'transcription' : '[йес]', 'rus' : 'да'},
{'eng' : 'no', 'transcription' : '[нOу]', 'rus' : 'нет'},
{'eng' : 'not', 'transcription' : '[нот]', 'rus' : 'не'},
{'eng' : 'this', 'transcription' : '[зис]', 'rus' : 'этот'},
{'eng' : 'that', 'transcription' : '[зэт]', 'rus' : 'тот; что (союз); который'},
{'eng' : 'these', 'transcription' : '[зи:з]', 'rus' : 'эти'},
{'eng' : 'those', 'transcription' : '[зОуз]', 'rus' : 'те'},
{'eng' : 'many', 'transcription' : '[мЭни]', 'rus' : 'много (+ слово во множественном числе)'},
{'eng' : 'much', 'transcription' : '[мач]', 'rus' : 'много (+ слово в единственном числе)'},
{'eng' : 'few', 'transcription' : '[фъю:]', 'rus' : 'мало (+ слово во множественном числе)'},
{'eng' : 'little', 'transcription' : '[литл]', 'rus' : 'мало (+ слово в единственном числе); маленький'},
{'eng' : 'some', 'transcription' : '[сам]', 'rus' : 'несколько; немного; некоторое количество (в утверждениях)'},
{'eng' : 'any', 'transcription' : '[Эни]', 'rus' : 'несколько; немного; некоторое количество; какой-нибудь (в вопросах); никакой (в отрицаних); любой (в утверждениях)'},
{'eng' : 'somebody', 'transcription' : '[сАмбоди]', 'rus' : 'кто-то (в утверждениях)'},
{'eng' : 'anybody', 'transcription' : '[Энибоди]', 'rus' : 'кто-то (в вопросах), никто (в отрицаниях), все (в утверждениях)'},
{'eng' : 'nobody', 'transcription' : '[нОубоди]', 'rus' : 'никто'},
{'eng' : 'something', 'transcription' : '[сАмсинг]', 'rus' : 'что-то (в утверждениях)'},
{'eng' : 'anything', 'transcription' : '[Энисинг]', 'rus' : 'что-то (в вопросах), ничто (в отрицаниях), всё (в утверждениях)'},
{'eng' : 'nothing', 'transcription' : '[насинг]', 'rus' : 'ничто'},
{'eng' : 'here', 'transcription' : '[хИэ]', 'rus' : 'здесь; сюда'},
{'eng' : 'there', 'transcription' : '[зЭэ]', 'rus' : 'там; туда'},
{'eng' : 'now', 'transcription' : '[нAу]', 'rus' : 'сейчас, теперь'},
{'eng' : 'again', 'transcription' : '[эгЭйн]', 'rus' : 'снова, опять'},
{'eng' : 'then', 'transcription' : '[зэн]', 'rus' : 'потом; тогда'},
{'eng' : 'than', 'transcription' : '[зЭн]', 'rus' : 'чем (при сравнении)'},
{'eng' : 'already', 'transcription' : '[о:лрЭди]', 'rus' : 'уже'},
{'eng' : 'just', 'transcription' : '[джаст]', 'rus' : 'только что; просто (прямо, как раз); только; справедливый'},
{'eng' : 'still', 'transcription' : '[стил]', 'rus' : '(всё) еще'},
{'eng' : 'yet', 'transcription' : '[йет]', 'rus' : 'еще (не)'},
{'eng' : 'almost', 'transcription' : '[O:лмоуст]', 'rus' : 'почти'},
{'eng' : 'several', 'transcription' : '[сЭвэрэл]', 'rus' : 'несколько'},
{'eng' : 'very', 'transcription' : '[вЭри]', 'rus' : 'очень'},
{'eng' : 'every', 'transcription' : '[Эври]', 'rus' : 'каждый'},
{'eng' : 'each', 'transcription' : '[и:ч]', 'rus' : 'каждый (по отдельности)'},
{'eng' : '(an)other', 'transcription' : '[(эн)Азэр]', 'rus' : 'другой'},
{'eng' : 'all', 'transcription' : '[о:л]', 'rus' : 'все; всё; весь'},
{'eng' : 'such', 'transcription' : '[сач]', 'rus' : 'такой'},
{'eng' : 'so', 'transcription' : '[сOу]', 'rus' : 'так; таким образом; итак; поэтому'},
{'eng' : 'up', 'transcription' : '[ап]', 'rus' : 'вверх'},
{'eng' : 'down', 'transcription' : '[дАун]', 'rus' : 'вниз'},
{'eng' : 'together', 'transcription' : '[тугЭзэр]', 'rus' : 'вместе'},
{'eng' : 'forward', 'transcription' : '[фО:р\'уэрд]', 'rus' : 'вперед; передний'},
{'eng' : 'even', 'transcription' : '[И:вэн]', 'rus' : 'даже'},
{'eng' : 'enough', 'transcription' : '[инAф]', 'rus' : 'достаточно'},
{'eng' : 'also', 'transcription' : '[О:лсоу]', 'rus' : 'также'},
{'eng' : 'too', 'transcription' : '[ту:]', 'rus' : 'тоже; слишком'},
{'eng' : 'only', 'transcription' : '[Оунли]', 'rus' : 'только'},
{'eng' : 'and', 'transcription' : '[энд]', 'rus' : 'и'},
{'eng' : 'or', 'transcription' : '[о:р]', 'rus' : 'или'},
{'eng' : 'but', 'transcription' : '[бат]', 'rus' : 'но'},
{'eng' : 'however', 'transcription' : '[хауЭвэр]', 'rus' : 'однако'},
{'eng' : 'because', 'transcription' : '[бикО:з]', 'rus' : 'потому что, так как'},
{'eng' : 'if', 'transcription' : '[иф]', 'rus' : 'если; ли'},
{'eng' : '(al)though', 'transcription' : '[(о:л)зОу]', 'rus' : 'хотя'},
{'eng' : 'be', 'transcription' : '[би:]', 'rus' : 'быть, являться'},
{'eng' : 'do', 'transcription' : '[ду:]', 'rus' : 'делать'},
{'eng' : 'have', 'transcription' : '[хэв]', 'rus' : 'иметь'},
{'eng' : 'can', 'transcription' : '[кэн]', 'rus' : 'мочь (быть в состоянии)'},
{'eng' : 'may', 'transcription' : '[мэй]', 'rus' : 'мочь (иметь разрешение)'},
{'eng' : 'go', 'transcription' : '[гOу]', 'rus' : 'идти; ехать; уходить; уезжать'},
{'eng' : 'find', 'transcription' : '[файнд]', 'rus' : 'находить'},
{'eng' : 'hold', 'transcription' : '[хOулд]', 'rus' : 'держать'},
{'eng' : 'stand', 'transcription' : '[стэнд]', 'rus' : 'стоять'},
{'eng' : 'sit', 'transcription' : '[сит]', 'rus' : 'сидеть'},
{'eng' : 'hear', 'transcription' : '[хИэ]', 'rus' : 'слышать'},
{'eng' : 'win', 'transcription' : '[уин]', 'rus' : 'побеждать'},
{'eng' : 'get', 'transcription' : '[гет]', 'rus' : 'получать; добираться; становиться'},
{'eng' : 'make', 'transcription' : '[мэйк]', 'rus' : 'делать (изготовлять)'},
{'eng' : 'come', 'transcription' : '[кам]', 'rus' : 'приходить, приезжать'},
{'eng' : 'become', 'transcription' : '[бикАм]', 'rus' : 'становиться'},
{'eng' : 'run', 'transcription' : '[ран]', 'rus' : 'бежать'},
{'eng' : 'see', 'transcription' : '[си:]', 'rus' : 'видеть'},
{'eng' : 'write', 'transcription' : '[райт]', 'rus' : 'писать'},
{'eng' : 'fall', 'transcription' : '[фо:л]', 'rus' : 'падать'},
{'eng' : 'wear', 'transcription' : '[уЭэр]', 'rus' : 'носить (одежду); одежда'},
{'eng' : 'take', 'transcription' : '[тэйк]', 'rus' : 'брать'},
{'eng' : 'give', 'transcription' : '[гив]', 'rus' : 'давать; дарить'},
{'eng' : 'forgive', 'transcription' : '[фэргИв]', 'rus' : 'прощать'},
{'eng' : 'forget', 'transcription' : '[форгЭт]', 'rus' : 'забывать'},
{'eng' : 'eat', 'transcription' : '[и:т]', 'rus' : 'кушать'},
{'eng' : 'lie', 'transcription' : '[лай]', 'rus' : 'лежать; лгать; ложь'}];